"""empty message

Revision ID: 7d0db930f440
Revises: 
Create Date: 2020-04-24 19:34:04.275425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d0db930f440'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'models')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('models', mysql.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
