"""empty message

Revision ID: edf2aaebad15
Revises: 7d0db930f440
Create Date: 2020-04-24 19:35:19.388354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf2aaebad15'
down_revision = '7d0db930f440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('models', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'models')
    # ### end Alembic commands ###
