
HTTP_OK = 200
HTTP_CREATE_OK = 201


USER_ACTION_LOGIN = "login"
USER_ACTION_REGISTER = "register"
USER_ACTION_YZM = 'useryzm'

ARTICLE_ACTION_CREATE = "create"
ARTICLE_ACTION_MODIFY = "modify"
ARTICLE_ACTION_DELETE = "delete"
ARTICLE_ACTION_SEARCH_ONE = "searchone"
ARTICLE_ACTION_SEARCH = "search"




USER_EXIST = 205
USER_NOT_EXIST = 206
USER_NOT_LOGIN = 207

ARTICLE_NOT_EXIST = 306

REQUEST_OK = 200
REQUEST_NO = 201

SEND_CODE_OK = 200
SEND_CODE_ERROR = 400

